version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/single" # Location of package manifests
    schedule:
      interval: "daily"
      timezone: "Europe/London"
      time: "05:00"
    assignees:
      - "modem7"
    labels:
      - "dependencies"

  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/dual" # Location of package manifests
    schedule:
      interval: "daily"
      timezone: "Europe/London"
      time: "05:00"
    assignees:
      - "modem7"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/London"
      time: "05:00"
    assignees:
      - "modem7"
    labels:
      - "dependencies"