name: Docker build CI Single

on:
  push:
    paths:
      - single/Dockerfile
  pull_request:
    paths:
      - single/Dockerfile
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest
    name: Set up Docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./single/Dockerfile
          pull: false
          push: false